# .github/workflows/deploy.yml
name: CI

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Playwright
      run: npx playwright install

    - name: Install dependencies
      run: npm install

    - name: Install ts-node and TypeScript
      run: npm install ts-node typescript --save-dev

    - name: Run tests
      run: npm run test
      continue-on-error: true

    - name: Generate Allure report 
      run: npm run allure:generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
